### ISSUE TITLE
The MultiJob shouldn't consume an executor

### ISSUE THREAD

**Issue by hagzag** [jenkinsci/tikal-multijob-plugin#10]
A deadlock can be encountered if there aren't enough executors, because the MultiJob is taking one up. For example, a Jenkins master with only one executor and no slaves can never use the MultiJob without deadlocking.
I marked this a bug, because this is exactly the same issue that came up with Matrix jobs, and that was considered a bug. See: JENKINS-936 [https://issues.jenkins-ci.org/browse/JENKINS-936]

Also monitored @: https://issues.jenkins-ci.org/browse/JENKINS-14204

**Comment by mpestritto** [comment]
Really old - but would be helpful  👍

**Comment by yotamshapira** [comment]
Multi jobs can run steps other than triggering sub-jobs, e.g. running shell scripts, so I’m not sure about this

**Comment by mpestritto** [comment]
Optional ?

**Comment by yotamshapira** [comment]
Sounds good :)

**Comment by yorammi** [comment]
Deprecated. @hagzag, re-open if still relevant

**Comment by smehrbrodt** [comment]
Seeing this and the Jira ticket is resolved, but can't see any solution.
I still have the problem that the multijob takes up one node, the child job is scheduled behind the multijob build and waits forever.

**Comment by lukiszlak** [comment]
> Seeing this and the Jira ticket is resolved, but can't see any solution.
> I still have the problem that the multijob takes up one node, the child job is scheduled behind the multijob build and waits forever.

Resolution is "Not a Defect" soo there was no fix.
They just assume that this is the way it should work.
Which is sad because it could help to have an option like this :(
