### ISSUE TITLE
a multijob, launching the same job in different phases with different parameters, shows on a view they run both 

### ISSUE THREAD

**Issue by dannftk** [jenkinsci/tikal-multijob-plugin#112]
actually, I am observing the following picture: if I have a multijob with the same sub-job being run in different phases one-by-one, not concurrently, upon starting up the multijob I see the appearance as though the phases had started simultaneously, along with the jobs showing they are working in parallel, but they are not, and shall not. Essentially and actually, only one instance of the job has started and been running. 
What I expect to see for the phases and the same jobs in different phases in the view not to look like they are running at the same time but at a time

Below here the picture comes. What could it be?
![screenshot from 2017-04-09 15-21-48](https://cloud.githubusercontent.com/assets/1688066/24837252/ca710d20-1d40-11e7-81a5-7165b4e4d846.png)

**Comment by dannftk** [comment]
and moreover, accidentally it does not activate the second phase upon finishing the first believing the second phase has already finished

**Comment by ptrsny** [comment]
A couple of month ago I  had the same problem and tried to fix it I Created a pull request for my solution [Pull Request](https://github.com/jenkinsci/tikal-multijob-plugin/pull/126)

It would be nice if you can tell me if it helps or not.

**Comment by AlexeyUzhva** [comment]
Would you please merge it? Need that also.

**Comment by ptrsny** [comment]
I am not able to merge it. @cohencil told me he will do it, but nothing since several weeks. Maybe you can tell him to merge it.

**Comment by AlexeyUzhva** [comment]
@cohencil , would you please do so!

Can't do that myself either, still need that and would greatly appreciate if you could do so.

**Comment by yorammi** [comment]
Is this still relevant? According to the above comments, a fix has already been merged for this.
@dannftk/@ptrsny/@AlexeyUzhva - can anyone of you confirm that it is fixed?
