### ISSUE TITLE
Job indirectly included multiple times in a multijob is sometimes only built once

### ISSUE THREAD

**Issue by zdave** [jenkinsci/tikal-multijob-plugin#117]
Create the following multijob setup:

    multijob_1
       phase 1 (parallel)
          multijob_2
             phase 1
                regular_job_1
          multijob_3
             phase 1
                regular_job_1

Build multijob_1.

Sometimes you will get two separate regular_job_1 builds (as expected), but sometimes you will only get a single regular_job_1 build, referenced from both the multijob_2 build and the multijob_3 build!

This does not seem to happen if the phase in multijob_1 is serial rather than parallel. It also does not seem to happen if regular_job_1 is included twice directly in multijob_1, ie without multijob_2/3 inbetween.

**Comment by zdave** [comment]
This is possibly the same as #112.

**Comment by cohencil** [comment]
Thanks for your notice, I'll look into it

**Comment by cohencil** [comment]
Does regular_job_1 configured to 'Execute concurrent builds if necessary' ?

**Comment by cohencil** [comment]
This behaviour you're describing might be related to an insufficient # of executors.
Please reopen if that doesn't help
