### ISSUE TITLE
Resume Build functionality only available to admins

### ISSUE THREAD

**Issue by travisofthenorth** [jenkinsci/tikal-multijob-plugin#118]
The "Resume Build" button is no longer available since this commit: https://github.com/jenkinsci/tikal-multijob-plugin/commit/2424cec7a099fe4392f052a754fadc28de9f8d86

I understand that this was a security fix, but would it be possible to put a proper permission in place? The `job.build` permission seems like a pretty sane user permission for this feature.

**Comment by travisofthenorth** [comment]
I am happy to throw together a PR, but I am not familiar with the Jenkins code and so I'm not sure how to query the proper permission. If someone could advise on how to do that, I'll set up a PR.

**Comment by cohencil** [comment]
Thanks for your input, I'll search for a better permission

**Comment by cohencil** [comment]
Fixed. Resume Build is now attached to Job.Build.
Will be reflected in next release.

**Comment by madihakh** [comment]
I am not able to view `Resume Build` button for my multijob pipeline configuration.  i am login as `anonymous`. According to this fix I understand that, as an `anonymous`  user I am allow to click/see `Build Now` pipeline in this way i should allow to perform `Resume build` action. But this button is not visible to me. Can you please guide?
