### ISSUE TITLE
When running one job several times in same phase, all console links point to the same last console url

### ISSUE THREAD

**Issue by TheNicow** [jenkinsci/tikal-multijob-plugin#12]
I want to launch one job several times in parallel in the same phase, it seems to work correctly, but in the results view, console links all point to the same console url, which is the last one.
I'm not sure if this issue is restricted to console link, or if it also concerns status, duration and so on.

**Comment by yorammi** [comment]
I'm closing this issue as deprecated. @TheNicow - please re-open if still relevant
