### ISSUE TITLE
Mult-Job With Same Job

### ISSUE THREAD

**Issue by wtlinnertz** [jenkinsci/tikal-multijob-plugin#120]
When running a multi-job using the same sub job with different parameters the visualization show all jobs running at the same time.  Also if you run the same job in parallel and click on a flashing job it takes you to the wrong job (same job different parameters).

**Comment by braunman** [comment]
I have same problems )

**Comment by heisian** [comment]
Can confirm - These are all the same job with different parameters, but they all show the same job even though they are different:

![screen shot 2017-12-21 at 4 40 23 pm](https://user-images.githubusercontent.com/4141828/34280602-bee3d0e0-e66d-11e7-856b-876a01a0ad49.png)

**Comment by mpestritto** [comment]
I just ran into this as well -- can you confirm that the jobs do execute properly ( with different parameters ) but just do not display properly on the job view ?
Thanks.

**Comment by yorammi** [comment]
You can confirm this with the build log where you can find that 2 different instances of the same sub-job activated. This is only a view issue.

**Comment by heisian** [comment]
@yorammi Yes, agreed, a view-only issue - clicking the links in the console output sends you to the correct jobs.

**Comment by ptrsny** [comment]
Please tell me if this is helping or not.

**Comment by yorammi** [comment]
Is this still relevant? According to the above comment, a fixed already been fixed. @wtlinnertz - please re-open if this is not fixed.

**Comment by heisian** [comment]
The multi job page no longer shows the same job, but now also doesn't show any status of the jobs:
![screen shot 2018-06-07 at 9 05 38 am](https://user-images.githubusercontent.com/4141828/41111826-09115d16-6a32-11e8-9123-08b4dd804fb0.png)

The build job page, as always, however, shows all jobs just fine:
![screen shot 2018-06-07 at 9 06 24 am](https://user-images.githubusercontent.com/4141828/41111857-17e47986-6a32-11e8-8350-3689765a5ab6.png)
