### ISSUE TITLE
No API inspection of a multijob

### ISSUE THREAD

**Issue by didrocks** [jenkinsci/tikal-multijob-plugin#13]
Hey,

I was switching to this plugin to get a clear view and a better stack rather than using downstream + join plugin + build pipelines. Thanks for your awesome work!

However, I'm trying to get from the api some test result to publish in an external dashboard and I need to publish the downstream (subtasks) seperately. One solution is to use some fingerprints, but I think multijob can provide a better way.

I can't directly use the downstream task some are shared between multiple multijob jobs, so I need to get the build revision explicitely.

Also, a way to retrieve which downstream job is part of which phase and how phases are chaining through the API would be awesome!

**Comment by yorammi** [comment]
I'm closing this issue as deprecated. @didrocks - please re-open if still relevant
