### ISSUE TITLE
No recent release notes

### ISSUE THREAD

**Issue by jiangty-addepar** [jenkinsci/tikal-multijob-plugin#137]
Hi, I noticed there's been recent updates to this plugin, but no release notes have been posted since 1.2.7: https://plugins.jenkins.io/jenkins-multijob-plugin

Can someone update the release notes so we can know if there are breaking changes?

**Comment by yorammi** [comment]
I've updated the latest versions (1.28-1.30) release notes

**Comment by jiangty-addepar** [comment]
Thanks!
