### ISSUE TITLE
"[?]" before phase name?

### ISSUE THREAD

**Issue by keshlam** [jenkinsci/tikal-multijob-plugin#138]
Apologies if this is a FAQ... We just did a bulk rename of Jenkins projects, and after doing so we've noticed that some of the phase names in our multijob projects are now displayed with **[?]** in front of them. I haven't yet found any documentation that explains what this mark is trying to tell me.

(It's possible that these were present earlier and I just didn't notice them...)

Help?

**Comment by vlsi** [comment]
This means the phase is conditional:  https://github.com/vlsi/tikal-multijob-plugin/blob/e6070daa7300e6c5f45d46562e5d68257f85f13b/src/main/resources/com/tikal/jenkins/plugins/multijob/views/JobColumn/column.jelly#L8

**Comment by yorammi** [comment]
Indeed, this is an indicator that this phase is conditional. @keshlam, can we close the issue or you think we should change/add/do something with it?

**Comment by keshlam** [comment]
Yep, we can close it. Sorry about that.
