### ISSUE TITLE
MultiJob does not build Pipeline jobs

### ISSUE THREAD

**Issue by ramkama** [jenkinsci/tikal-multijob-plugin#152]
Hello,

  Need your help here guys. I've diferrent Pipeline Jobs and I need to configure them using the Multijob Plugin Job as Upstream and downstream jobs. I'm unable to view or execute these upstream and downstream jobs which are created using Pipelines via Multijob Plugin Master Job. How do I fix this issue?

I'm using latest Multijob Plugin v1.30

**Comment by bmdepesa** [comment]
I am also seeing this issue. 

I have a MultiJob which setup to execute 3 pipeline jobs. The phase name is displayed in the job list overview, but not the pipeline jobs, and nothing is built.

**Comment by robertcowher** [comment]
I'm seeing the problem as well. No pipeline jobs display in the UI and the pipeline jobs aren't run.

**Comment by sabf81** [comment]
same problem... is there an ETA when it will be fixed or any workaround?

**Comment by asthomasdk** [comment]
Also seeing this and need a good visual solution. 

Seems like the only way to key pipeline jobs together is to write a pipeline that handles this or set up triggers on the individual jobs for them to be executed in the right order. 

This doesn't give the nice UI that multijob does on execution though.

**Comment by OlgaPaw** [comment]
In my case I can see pipeline subjobs, but they are never called
![image](https://user-images.githubusercontent.com/11198678/44077608-82c4a332-9fa4-11e8-8f91-48fa5f86ed7e.png)

**Comment by amrutprabhu** [comment]
Facing the same issue, the pipeline job does not appear as a sub job and also does not execute it.

**Comment by suvirp** [comment]
Is anyone working on this? There was a workaround provided in https://issues.jenkins-ci.org/browse/JENKINS-38825, which was working for us but now we cannot upgrade to newer version as that code doesn't seem to compatible with new changes

**Comment by wdgang** [comment]
To be clear, using Trigger other projects step described in JENKINS-38825 is not a workaround to this issue, it's a totally different way to triggering the downstream pipeline job, the problem with Multi-job is still there, hope there's a fix soon.

**Comment by yorammi** [comment]
Version 1.32 fix this issue
