### ISSUE TITLE
Feature Request to specify a delay before starting jobs in parallel

### ISSUE THREAD

**Issue by clhpoole** [jenkinsci/tikal-multijob-plugin#158]
I have a multi-job with 29 jobs in one phase but I don't want all of them to start at once. I'd like a delay of a few seconds before starting a job. It could be global, e.g. wait three seconds before starting the next job, or per job, e,g.  wait five seconds before starting this job.

Thanks for considering this.

Cheers,
 Cheryl

**Comment by cloudyster** [comment]
Hi Cheryl,

we have some similar needs to delay some of our sub-jobs so I added
a new parameter that allows to calculate a sub-job;s quiet period based 
on the job's index; see #193. Feel It would be nice if you could test the forked
plugin.

Cheers,
Christian
