### ISSUE TITLE
Need to filter jobs in Multijob view

### ISSUE THREAD

**Issue by uttamk** [jenkinsci/tikal-multijob-plugin#16]
Currently, a multijob view shows all the multijob projects. This view can get cluttered. A nice thing to have would be to choose which multijob project to show in a view. To give an example, we used the multijob plugin to good effect for having parallel tasks in our deployment for various environments. With a custom multijob view, I can have a tab for each environment with one multijob project in it. It gives a neater dashboard.

**Comment by felyppers** [comment]
No news on this?
