### ISSUE TITLE
Disable/enable job or phase without disabling the "regular" job itself

### ISSUE THREAD

**Issue by hagzag** [jenkinsci/tikal-multijob-plugin#4]
Whilst working with Build Phases conducted of regular jobs, we need the ability to disable a certain Job within the Phase or the Flow of the build. Although as of today disabling a certain Job will also disable it in  a "CI scope" or its standalone state [out of the MultiJob scope].
so we need to add a check box at each phase level which will disable that certain job or Phase all together,  what would be nice is to configure it once and it will be back to normal the next time you execute the MultiJob or permanent.
This Feature request is also available @: https://issues.jenkins-ci.org/browse/JENKINS-14600 
Inspired by: https://wiki.jenkins-ci.org/display/JENKINS/Multijob+Plugin?focusedCommentId=62620522#comment-62620522

**Comment by yorammi** [comment]
Deprecated. @hagzag, re-open if still relevant
